### ISSUE TITLE
Missing line in TSVGIconImageListEditor.UpdateGUI

### ISSUE THREAD

**Issue by Lajos-Juhasz** [EtheaDev/SVGIconImageList#153] opened 2020-12-22 09:27 UTC
I still have no local repository to send a pull request for this one. When there is no image selected the Category is enabled and trying to exit it results in Access Violation. It should be adjusted same as NameEdit:

CategoryEdit.Enabled:= LIsItemSelected;

**Comment by carloBarazzetta** [comment] 2020-12-22 14:32
I cannot reproduce the problem: when there isn't any category the "All" item is always present...
Can you explain me the steps to reproduce the error?

**Comment by Lajos-Juhasz** [comment] 2020-12-24 10:43
Place a new TSVGIconImageCollection on the form. Double click it to invoke the component editor. Focus the CategoryEdit enter some value and try to click on another component in the TSVGIconImageListEditor.CategoryEditExit the SelectedIcon = nil this will cause access violation on the line:

if SelectedIcon.Category <> CategoryEdit.Text then

**Comment by carloBarazzetta** [comment] 2020-12-26 09:36
Fixed in 2.2.2 version

**Closed by carloBarazzetta** 2020-12-26 09:36 UTC
